version: 3.8.{build}
branches:
  only:
  - master
image: Visual Studio 2019
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
after_build:
- ps: dotnet pack /p:Version=$env:APPVEYOR_BUILD_VERSION src\Elmah.Io.AspNetCore\Elmah.Io.AspNetCore.csproj --output artifacts
- ps: dotnet pack /p:Version=$env:APPVEYOR_BUILD_VERSION src\Elmah.Io.AspNetCore.TagHelpers\Elmah.Io.AspNetCore.TagHelpers.csproj --output artifacts
- ps: dotnet pack /p:Version=$env:APPVEYOR_BUILD_VERSION src\Elmah.Io.AspNetCore.HealthChecks\Elmah.Io.AspNetCore.HealthChecks.csproj --output artifacts
test:
  assemblies:
    only:
    - test\Elmah.Io.AspNetCore.Tests\bin\**\Elmah.Io.AspNetCore.Tests.dll
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: RQWqfWK1hfN1yqTFr0rFyVweuhfIN6nMVRER6HqRe7m197hEqjvlpeEy/UEIaCwu